### ISSUE TITLE
Summary Evaluation is not visible on Experiments WebUI

### ISSUE THREAD

**Issue by yusuke-intern** [langchain-ai/langsmith-sdk#830] opened 2024-07-01 03:14 UTC
I implemented this following the video, but the f1-score is not displayed on the WebUI.
https://www.youtube.com/watch?v=zMgrHzs_cAg

Looking at the evaluators, the calculations are being done, the functions are executed properly, and the values are calculated correctly. However, it is not being displayed as s chart.

**Comment by hinthornw** [comment] 2024-07-01 16:25
Could you share please share code?

**Comment by yusuke-intern** [comment] 2024-07-02 04:32
@hinthornw 
Sure, I used `summary_evaluators`.

```Python
def precision(runs: list, examples: list):
    true_positives = sum([1 for run, example in zip(runs, examples) if run.outputs["is_target"] == example.outputs["is_target"]])
    false_positives = sum([1 for run, example in zip(runs, examples) if run.outputs["is_target"] != example.outputs["is_target"]])
    return {"score": true_positives / (true_positives + false_positives), "key": "precision"}

def recall(runs: list, examples: list):
    true_positives = sum([1 for run, example in zip(runs, examples) if run.outputs["is_target"] == example.outputs["is_target"]])
    false_negatives = sum([1 for run, example in zip(runs, examples) if run.outputs["is_target"] != example.outputs["is_target"]])
    return {"score": true_positives / (true_positives + false_negatives), "key": "recall"}

def f1_score_summary_evaluator(runs: List[Run], examples: List[Example]) -> dict:
    true_positives = 0
    false_positives = 0
    false_negatives = 0
    for run, example in zip(runs, examples):
        # Matches the output format of your dataset
        reference = example.outputs["is_target"]
        # Matches the output dict in `predict` function below
        
        prediction = run.outputs.get("is_target",None)
        if prediction == None:
            false_negatives += 1
            continue
        
        if reference and prediction == reference:
            true_positives += 1
        elif prediction and not reference:
            false_positives += 1
        elif not prediction and reference:
            false_negatives += 1
    if true_positives == 0:
        return {"key": "f1_score", "score": 0.0}

    precision = true_positives / (true_positives + false_positives)
    recall = true_positives / (true_positives + false_negatives)
    f1_score = 2 * (precision * recall) / (precision + recall)
    return {"key": "f1_score", "score": f1_score}


results = evaluate(
    lambda inputs: label_text(inputs["body"]),
    data=client.list_examples(dataset_name=dataset_name, as_of="latest"),
    evaluators=[correct_label],
    summary_evaluators=[f1_score_summary_evaluator,precision, recall],
    experiment_prefix="pickup-gemini-subset",
)

```

**Comment by yusuke-intern** [comment] 2024-07-02 05:39
@hinthornw 
The code used in the video is same as the current version?
https://www.youtube.com/watch?v=zMgrHzs_cAg

**Comment by whatever-afk** [comment] 2024-07-02 06:20
Same issue, the metrics are not being displayed in the UI despite `results._summary_results` shows the `EvaluationResult` with the metrics.

**Comment by mobiware** [comment] 2024-07-05 21:15
We're having the same issue.
Official documentation says the summary evaluation results should be visible in the experiments UI, but they're not
https://docs.smith.langchain.com/how_to_guides/evaluation/evaluate_llm_application#use-a-summary-evaluator

**Comment by mobiware** [comment] 2024-07-05 22:22
Also the summary evaluation results aren't really exposed in an official manner in the Langsmith SDK. The only way to programmatically access them is to use `results._summary_results` as said by @whatever-afk, which is not a public API

**Comment by mobiware** [comment] 2024-07-08 09:24
@0d431 we didn't have any issue returning multiple evaluation results though. Here's what our summary evaluator function looks like:
```
def evaluate_precision_recall(
    runs: Sequence[Run], examples: Sequence[Example]
) -> EvaluationResults:
    true_positives_count = 0
    detected_count = 0
    reference_count = 0

    for example, run in zip(examples, runs):
        reference = set((example.outputs and example.outputs.get("data")) or [])
        detected = set((run.outputs and run.outputs.get("data")) or [])
        true_positives = detected.intersection(reference)

        true_positives_count += len(true_positives)
        detected_count += len(detected)
        reference_count += len(reference)

    precision = true_positives_count / detected_count
    recall = true_positives_count / reference_count
    f_score = 2 * precision * recall / (precision + recall)

    return EvaluationResults(
        results=[
            EvaluationResult(
                key="precision",
                score=precision,
            ),
            EvaluationResult(
                key="recall",
                score=recall,
            ),
            EvaluationResult(
                key="f_score",
                score=f_score,
            ),
        ]
    )
```

**Comment by whatever-afk** [comment] 2024-07-10 07:02
@0d431 i think this works only for a single run i.e when you are evaluating the output vs the reference for each, the code @mobiware actually output the results as expected 
```python
{
  "results": [
    {
      "key": "precision",
      "score": 0.8974358974358975,
      "evaluator_info": {}
    },
    {
      "key": "recall",
      "score": 0.9722222222222222,
      "evaluator_info": {}
    },
    {
      "key": "f_score",
      "score": 0.9333333333333333,
      "evaluator_info": {}
    }
  ]
}
````
However, the issue is we are still unable to see the results in the UI.

**Comment by shawnli-capix** [comment] 2024-07-18 00:01
+1. Facing the same issue as well. Summary Metrics can only be viewed by accessing `results._summary_results` in code, but the metrics don't show up in the web UI.

**Comment by mobiware** [comment] 2024-07-18 18:05
In fact as of today I can now see the summary evaluation in Langsmith web UI, including for past Experiments !

@hinthornw should we open a separate ticket for the other issue mentioned in this ticket, i.e. the fact that after running `evaluate()` the summary results are available only on `ExperimentResults._summary_results` which is a private attribute. It would be nice to have a public accessor to this attribute

**Comment by shawnli-capix** [comment] 2024-07-18 19:45
@mobiware What did you change that makes the summary evaluation show up in the LangSmith Web UI?

**Comment by hinthornw** [comment] 2024-08-07 17:50
Hi all! There were a few versions of langsmith where the summary metrics were no longer being reported. If you upgrade to any of the past 5 or so versions, this should be fixed.

**Comment by hinthornw** [comment] 2024-08-26 04:10
I believe this was resolved in the aforementioned changes. LMK if you believe otherwise

**Closed by hinthornw** 2024-08-26 04:10 UTC

**Comment by catdumitru** [comment] 2024-08-29 21:24
Having the same issue. 

@hinthornw by "upgrade langsmith" are you referring to updating the local version of the `langsmith` package? That doesn't seem to fix the UI issue, the summary score only appears as a column in the list of experiments for a dataset, not in the detailed view though. In the video shared earlier, the f1 score appears below the list of runs, but that's not the case when running the code locally.
